load("//devtools/python/blaze:pytype.bzl", "pytype_strict_library")

pytype_strict_library(
    name = "test_fuzzingclient",
    srcs = ["test_fuzzingclient.py"],
    deps = ["//third_party/py/websocket"],
)
